### ISSUE TITLE
Change voting model to allow for 'abstain'

### ISSUE THREAD

**Issue by chrisjrn** [lca2017/symposion#2]
There should be an "abstain" option for votes, which will not count towards the review score for a proposal, but still counts as a review and has a comment.

**Comment by ghost** [comment]
My initial view is that it should just be an addition to the CHOICES for an actual "0" vote. (if you look at the score_expression() method +0 and -0 actually get multiplied by one while -1 and +1 get multiplied by 3.

We need to add a constraint in there to require a reason for abstention. Should it be another field in the model or just as a comment?
