### ISSUE TITLE
Need to create proposal models for CFP

### ISSUE THREAD

**Issue by ghost** [lca2017/symposion#9]
Need to create new models for
- talks
- tutorials
- miniconfs

**Comment by chrisjrn** [comment]
And miniconfs.

**Comment by ghost** [comment]
So for the CFP, we create a proposal for miniconfs, and then later we'll create proposal type for miniconf talks themselves?

**Comment by chrisjrn** [comment]
Yes indeed

**Comment by chrisjrn** [comment]
Done!
